trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Job1
  steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo "This is Job 1"
          echo "Running sequentially"


