trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Job1
  steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo "This is Job 1"
          echo "Running sequentially"

- job: Job2
  dependsOn: Job1   # Job2 will run only after Job1 completes
  steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo "This is Job 2"
          echo "Running after Job 1 completes"
