trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Job1
  steps:
  - task: S3Download@1
    inputs:
      awsCredentials: 'aws'
      regionName: 'us-east-1'
      bucketName: 'azure-bucket-1'
      globExpressions: '**'
      targetFolder: '/tmp'

